dist: trusty
sudo: false
language: node_js
node_js:
  - "10"
os:
  - linux
before_install:
  # Use a virtual display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install latest chrome.
  - export CHROME_BIN=chromium-browser
install:
  - npm install
script:
  - npm run lint log4ngx
  - npm run test:travis
  - npm run coverage:travis
